version: 2
updates:
  - package-ecosystem: docker
    directory: "/kubernetes/monitoring/test/ab"
    schedule:
      interval: daily
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/monitoring/test/postmannewman"
    schedule:
      interval: daily
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/postgres"
    schedule:
      interval: daily
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/mysql"
    schedule:
      interval: daily
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/nginx"
    schedule:
      interval: daily
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/mongodb"
    schedule:
      interval: daily
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/monitoring/jenkins"
    schedule:
      interval: daily
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/wlp"
    schedule:
      interval: daily
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/rabbitmq"
    schedule:
      interval: daily
    assignees:
      - yurake
