version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 15eac2dc9551ea8566757f925a7f33f2677d2f9e106785390b872dc1a8bfc042
    docker:
      - image: "cimg/openjdk:14.0.1"
    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/parent-pom/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests parent-pom
          working_directory: application/parent-pom
          command: |
            mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/parent-pom/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/webapp-service/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests webapp-service
          working_directory: application/webapp-service
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/webapp-service/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-activemq-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests consumer-activemq-quarkus
          working_directory: application/consumer-activemq-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-activemq-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-hazelcast-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests consumer-hazelcast-quarkus
          working_directory: application/consumer-hazelcast-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-hazelcast-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-kafka-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests consumer-kafka-quarkus
          working_directory: application/consumer-kafka-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-kafka-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-rabbitmq-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests consumer-rabbitmq-quarkus
          working_directory: application/consumer-rabbitmq-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-rabbitmq-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-redis-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests consumer-redis-quarkus
          working_directory: application/consumer-redis-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-redis-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-activemq-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-activemq-quarkus
          working_directory: application/jaxrs-activemq-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-activemq-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-hazelcast-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-hazelcast-quarkus
          working_directory: application/jaxrs-hazelcast-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-hazelcast-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-kafka-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-kafka-quarkus
          working_directory: application/jaxrs-kafka-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-kafka-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-memcached-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-memcached-quarkus
          working_directory: application/jaxrs-memcached-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-memcached-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-mongodb-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-mongodb-quarkus
          working_directory: application/jaxrs-mongodb-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-mongodb-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-mysql-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-mysql-quarkus
          working_directory: application/jaxrs-mysql-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-mysql-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-postgres-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-postgres-quarkus
          working_directory: application/jaxrs-postgres-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-postgres-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-rabbitmq-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-rabbitmq-quarkus
          working_directory: application/jaxrs-rabbitmq-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-rabbitmq-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-redis-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-redis-quarkus
          working_directory: application/jaxrs-redis-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-redis-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/producer-kafka-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests producer-kafka-quarkus
          working_directory: application/producer-kafka-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/producer-kafka-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/randompublish-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests randompublish-quarkus
          working_directory: application/randompublish-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/randompublish-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/redis-mysql-helidon/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests redis-mysql-helidon
          working_directory: application/redis-mysql-helidon
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/redis-mysql-helidon/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/scheduled-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests scheduled-quarkus
          working_directory: application/scheduled-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/scheduled-quarkus/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/wlp-web-java-spring/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests wlp-web-java-spring
          working_directory: application/wlp-web-java-spring
          command: |
            ../../cc-test-reporter before-build
            mvn clean verify
            export JACOCO_SOURCE_PATH="src/main/java"
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/wlp-web-java-spring/pom.xml" }}
