apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlp
spec:
  selector:
    matchLabels:
      app: wlp
  replicas: 1
  template:
    metadata:
      labels:
        app: wlp
    spec:
      containers:
        - name: wlp
          image: yurak/wlp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          resources:
            limits:
              memory: 600Mi
              cpu: 500m
            requests:
              memory: 100Mi
              cpu: 100m
          volumeMounts:
            - name: wlp-config-volume
              mountPath: /config/jvm.options
              subPath: jvm-options
      volumes:
        - name: wlp-config-volume
          configMap:
            name: wlp-configmap
