apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-mysql-helidon
spec:
  selector:
    matchLabels:
      app: redis-mysql-helidon
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-mysql-helidon
    spec:
      containers:
        - name: redis-mysql-helidon
          image: yurak/redis-mysql-helidon:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
