name: Check for CI Target

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: get the current number of java pcojects
        working-directory: ./application
        run: echo "SOURCE_PROJECT=$(find . -name "pom.xml" | grep -v -e target -e src | wc -l | tr -d ' ')" >> $GITHUB_ENV
      - name: get java-ci.yml
        working-directory: ./.github/workflows
        run: echo "JAVACI_PROJECT=$(grep verify java-ci.yml | wc -l | tr -d ' ')" >> $GITHUB_ENV
      - name: check java-ci.yml
        run: |
          echo CURRENT: ${SOURCE_PROJECT}
          echo TARGET: ${JAVACI_PROJECT}
          test ${SOURCE_PROJECT} = ${JAVACI_PROJECT}
