name: e2e test on Minikube
on:
  push:
    paths: 
      - '.github/workflows/minikube-ci.yml'
  pull_request:

jobs:
  minikube-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: opsgang/ga-setup-minikube@v0.1.1
      with:
        minikube-version: 1.4.0
        k8s-version: 1.15.1
    - name: Testing
      run: |
        minikube config set vm-driver kvm2
        minikube config set kubernetes-version v1.15.1
        minikube start
        minikube update-context
        kubectl cluster-info
        kubectl get pods -n kube-system
